name: Build Solution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    - name: Build solution

      run: |
          dotnet build map1.csproj -c Release -o .\publish
       
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
          name: artifact
          path: ${{ github.workspace }}/**/*
